"""Pending human approvals — the queue §23's "vue sécurité" needs.

Until now Aegis worked purely as "refuse and tell the caller": a
require_human_validation verdict went back to whoever asked, and nothing
was kept. That is safe, but it means there is no such thing as a list of
things awaiting your approval, and no way to say yes to one after the
fact — the caller is long gone by the time a human looks.

This adds that queue, deliberately narrowly:

  - **One-shot.** An approval is consumed the first time it is used. It
    cannot become a standing permission by accident.
  - **Time-limited.** It expires (default 15 minutes), so an approval
    forgotten in the queue does not authorise anything tomorrow.
  - **Fingerprinted exactly.** The approval matches one action_type +
    target_path + description triple and nothing else. Descriptions here
    are code-generated and deterministic (`Write to {path}`, `Commit on
    {branch} in {repo}`), so a legitimate retry reproduces the same
    fingerprint while a *different* action cannot borrow the approval.

The engine (security/aegis_engine.py) stays DB-free and pure by design,
so this is consulted from AegisAgent, not from the engine.

Approving here does **not** replay the action. Nothing re-executes on the
user's behalf: the approval simply means the next identical attempt is
allowed through once. Replaying arbitrary stored actions would need a
dispatcher able to re-run anything, which is exactly the kind of
machinery a security gate should not own.

One deliberate consequence, verified in use: **a refusal is per-attempt,
not permanent.** Refusing leaves a `refused` row as the record of that
decision, but a later retry of the same action queues a fresh `pending`
one — because "no, not now" is not the same statement as "never, and
stop asking". The dedup above only prevents duplicate *pending* rows, so
an agent retrying in a loop after a refusal will re-ask. That is the
intended trade-off (a refusal must not silently become a permanent
block a user can't undo), but it means the queue is a work list, not an
audit log: read it as "what is being asked of me now", with the decided
rows as history beside it.
"""
from __future__ import annotations

import hashlib
import uuid
from datetime import UTC, datetime, timedelta
from enum import StrEnum

from sqlalchemy import DateTime, String, Text, select
from sqlalchemy.orm import Mapped, Session, mapped_column

from backend.memory.db import Base
from backend.core.event_hub import get_event_hub

DEFAULT_TTL_MINUTES = 15


class ApprovalStatus(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    REFUSED = "refused"
    # Approved and then actually used — kept distinct from APPROVED so the
    # queue can show that consent was spent, not merely granted.
    USED = "used"


class PendingApproval(Base):
    __tablename__ = "pending_approvals"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    fingerprint: Mapped[str] = mapped_column(String, index=True)
    action_type: Mapped[str] = mapped_column(String, index=True)
    description: Mapped[str] = mapped_column(Text)
    target_path: Mapped[str | None] = mapped_column(String, nullable=True)
    requesting_agent: Mapped[str] = mapped_column(String)
    reason: Mapped[str] = mapped_column(Text, default="")
    status: Mapped[str] = mapped_column(String, index=True, default=ApprovalStatus.PENDING)
    task_id: Mapped[str | None] = mapped_column(String, nullable=True)
    project_id: Mapped[str | None] = mapped_column(String, nullable=True, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime)
    decided_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)


def fingerprint_for(action_type: str, target_path: str | None, description: str) -> str:
    """Identify one specific action.

    Includes the description on purpose: an approval for "Commit on
    feature/x" must not authorise "Commit on main". Descriptions are
    generated by the calling tool, not by a model, so a genuine retry
    reproduces this exactly.
    """
    raw = "\x1f".join([action_type, target_path or "", description.strip()])
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _now() -> datetime:
    return datetime.now(UTC)


def _as_aware(value: datetime | None) -> datetime | None:
    """SQLite hands back naive datetimes; compare in UTC regardless."""
    if value is None:
        return None
    return value if value.tzinfo else value.replace(tzinfo=UTC)


def record_pending(
    session: Session,
    *,
    action_type: str,
    description: str,
    reason: str,
    target_path: str | None = None,
    requesting_agent: str = "unknown",
    task_id: str | None = None,
    project_id: str | None = None,
) -> PendingApproval:
    """Queue a refused action for later human decision.

    Re-refusing the same action returns the existing pending row rather
    than piling up duplicates — an agent that retries in a loop would
    otherwise flood the queue and bury the entries that matter.
    """
    fingerprint = fingerprint_for(action_type, target_path, description)
    existing = session.execute(
        select(PendingApproval).where(
            PendingApproval.fingerprint == fingerprint,
            PendingApproval.status == ApprovalStatus.PENDING,
        )
    ).scalar_one_or_none()
    if existing is not None:
        # Deliberately *not* published to §24.2: this is the same pending
        # item, not a new one. An agent retrying in a loop would otherwise
        # repeat the same validation.request on the dashboard and bury the
        # entries that matter — exactly what this dedup prevents in the
        # table.
        return existing

    entry = PendingApproval(
        id=str(uuid.uuid4()),
        fingerprint=fingerprint,
        action_type=action_type,
        description=description,
        target_path=target_path,
        requesting_agent=requesting_agent,
        reason=reason,
        status=ApprovalStatus.PENDING,
        task_id=task_id,
        project_id=project_id,
        created_at=_now(),
    )
    session.add(entry)
    session.commit()
    session.refresh(entry)
    # After the commit, never before: a client must not be told to
    # validate something that failed to persist.
    get_event_hub().publish("validation.request", to_dict(entry))
    return entry


def list_approvals(
    session: Session, *, status: str | None = None, project_id: str | None = None
) -> list[PendingApproval]:
    stmt = select(PendingApproval).order_by(PendingApproval.created_at.desc())
    if status is not None:
        stmt = stmt.where(PendingApproval.status == status)
    if project_id is not None:
        stmt = stmt.where(PendingApproval.project_id == project_id)
    return list(session.execute(stmt).scalars())


def get_approval(session: Session, approval_id: str) -> PendingApproval | None:
    return session.get(PendingApproval, approval_id)


def decide(
    session: Session,
    approval_id: str,
    *,
    approved: bool,
    ttl_minutes: int = DEFAULT_TTL_MINUTES,
) -> PendingApproval | None:
    """Record a human decision. Returns None if there is no such entry.

    Only a PENDING entry can be decided: re-approving something already
    used would silently mint a second consent from one human action.
    """
    entry = session.get(PendingApproval, approval_id)
    if entry is None or entry.status != ApprovalStatus.PENDING:
        return entry

    entry.status = ApprovalStatus.APPROVED if approved else ApprovalStatus.REFUSED
    entry.decided_at = _now()
    entry.expires_at = _now() + timedelta(minutes=ttl_minutes) if approved else None
    session.commit()
    session.refresh(entry)
    return entry


def consume_approval(
    session: Session, *, action_type: str, target_path: str | None, description: str
) -> PendingApproval | None:
    """Spend a live approval for this exact action, if one exists.

    Returns the entry when consent applied (and marks it USED), or None —
    in which case the caller must go on refusing. An expired approval is
    not consumed and is left visible in the queue as expired-by-time
    rather than being silently deleted.
    """
    fingerprint = fingerprint_for(action_type, target_path, description)
    entry = session.execute(
        select(PendingApproval)
        .where(
            PendingApproval.fingerprint == fingerprint,
            PendingApproval.status == ApprovalStatus.APPROVED,
        )
        .order_by(PendingApproval.decided_at.desc())
    ).scalars().first()

    if entry is None:
        return None

    expires_at = _as_aware(entry.expires_at)
    if expires_at is not None and expires_at < _now():
        return None

    entry.status = ApprovalStatus.USED
    session.commit()
    session.refresh(entry)
    return entry


def to_dict(entry: PendingApproval) -> dict:
    expires_at = _as_aware(entry.expires_at)
    return {
        "id": entry.id,
        "action_type": entry.action_type,
        "description": entry.description,
        "target_path": entry.target_path,
        "requesting_agent": entry.requesting_agent,
        "reason": entry.reason,
        "status": entry.status,
        "task_id": entry.task_id,
        "project_id": entry.project_id,
        "created_at": entry.created_at.isoformat(),
        "decided_at": entry.decided_at.isoformat() if entry.decided_at else None,
        "expires_at": expires_at.isoformat() if expires_at else None,
        "expired": bool(expires_at and expires_at < _now()),
    }
