"""Identifier une action, indépendamment de la façon dont on l'a écrite (HOS-224).

## Ce que l'empreinte précédente identifiait vraiment

`approvals.fingerprint_for` hache `action_type`, `target_path` et la
**description en toutes lettres**, jointes telles quelles. Son
commentaire justifie l'inclusion de la description par un argument
correct — « une approbation pour *Commit on feature/x* ne doit pas
autoriser *Commit on main* » — et s'appuie sur une hypothèse qui n'est
vraie que pour une partie des appelants :

> Descriptions are generated by the calling tool, not by a model.

Vrai pour `file_tools` et `git_tools`. **Faux** pour l'outil MCP
`aegis_check`, dont la description est écrite par le modèle, et pour
`POST /api/v1/security/evaluate`, dont elle vient du corps de la requête.

Mesuré :

    « Write to config.json to fix the port »  -> 24aa0d0bf698
    « Write config.json (port fix) »          -> 061db3be665d

Deux empreintes pour une seule action. Le « oui » de l'humain ne
s'applique jamais, une seconde demande est déposée, et rien ne dit
pourquoi. Une approbation qui ne marche pas en silence finit désactivée.

## Et le chemin ne l'était pas non plus

Quatre écritures du même fichier, quatre empreintes différentes :

    C:/p/config.json      C:\\p\\config.json
    c:/p/config.json      C:/p/../p/config.json

Sur Windows, ce n'est pas un cas de laboratoire : les chemins arrivent
d'un `Path`, d'une chaîne JSON, d'une saisie. Le défaut ne va que dans
le sens sûr — il refuse au lieu d'autoriser — mais il rend la fonctionnalité
inutilisable, ce qui revient au même une fois qu'on l'a désactivée.

## La règle retenue

L'identité d'une action est **structurée**, jamais rédigée :

    action_type + chemin canonique + discriminants triés

La description reste sur la ligne, pour que l'humain sache ce qu'il
approuve. Elle n'entre plus dans l'identité.

Ce qui distinguait légitimement deux actions dans la prose devient un
**discriminant nommé** : `git_tools.commit` passe `{"branch": "main"}`
au lieu de compter sur la phrase « Commit on main ». La garantie du
commentaire d'origine est donc conservée — et elle ne dépend plus de la
formulation.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any, Mapping

#: Le séparateur d'unité ASCII, comme dans la version précédente : il ne
#: peut pas apparaître dans un chemin ni dans un nom de discriminant, ce
#: qui empêche `("a", "b|c")` et `("a|b", "c")` de se confondre.
SEPARATEUR = "\x1f"


def canoniser_chemin(chemin: str | None) -> str:
    """Une seule écriture pour un seul fichier.

    `resolve()` fait le gros du travail — chemin absolu, `..` réduit,
    liens suivis. Deux ajouts nécessaires sur Windows : les séparateurs
    sont ramenés à `/`, et la casse est repliée parce que le système de
    fichiers ne la distingue pas. Replier la casse sous Linux serait
    faux : `Config.json` et `config.json` y sont deux fichiers.

    Un chemin qui ne se résout pas est rendu **normalisé mais non
    résolu** plutôt que rejeté : une approbation peut porter sur un
    fichier qui n'existe pas encore, ce qui est même le cas courant
    d'une création.
    """
    if not chemin:
        return ""
    try:
        texte = str(Path(chemin).resolve())
    except (OSError, RuntimeError, ValueError):
        texte = os.path.normpath(str(chemin))
    # L'ordre compte : `normcase` reconvertit les `/` en `\` sur Windows,
    # donc replier la casse **avant** d'uniformiser les séparateurs. Fait
    # dans l'autre sens, `c:/projet` ressortait en `c:\projet` et la
    # portée ne couvrait plus rien.
    texte = os.path.normcase(texte)
    texte = texte.replace(os.sep, "/")
    if os.altsep:
        texte = texte.replace(os.altsep, "/")
    # Sous Linux, l'antislash est un caractère de nom de fichier légal :
    # `os.altsep` y vaut None, et il survit donc, ce qui est correct.
    return texte


def canoniser_discriminants(discriminants: Mapping[str, Any] | None) -> str:
    """Sérialiser ce qui distingue deux actions par ailleurs identiques.

    Clés triées et séparateurs fixes : deux appelants qui construisent le
    même dictionnaire dans un ordre différent doivent produire la même
    empreinte, sans quoi on aurait remplacé l'instabilité de la prose par
    celle d'un ordre d'insertion.
    """
    if not discriminants:
        return ""
    return json.dumps({str(k): discriminants[k] for k in sorted(discriminants)},
                      sort_keys=True, separators=(",", ":"),
                      ensure_ascii=False, default=str)


def empreinte(action_type: str, target_path: str | None = None, *,
              discriminants: Mapping[str, Any] | None = None) -> str:
    """L'identité canonique d'une action.

    Ne prend **pas** la description : voir l'en-tête du module.
    """
    brut = SEPARATEUR.join([
        (action_type or "").strip().lower(),
        canoniser_chemin(target_path),
        canoniser_discriminants(discriminants),
    ])
    return hashlib.sha256(brut.encode("utf-8")).hexdigest()


def couvre(racine: str, chemin: str) -> bool:
    """`chemin` est-il sous `racine` ?

    Les deux sont canonisés d'abord — sans quoi une portée accordée sur
    `C:\\projet` ne couvrirait pas `C:/projet/src/a.py`, et le refus
    ressemblerait à un défaut de sécurité alors que ce serait un défaut
    d'écriture.

    La comparaison se fait sur des `PurePosixPath` après canonisation :
    `is_relative_to` sur des chaînes brutes accepterait `C:/projet-bis`
    comme étant sous `C:/projet`, ce qu'un simple `startswith` fait et
    qui serait une évasion de portée.
    """
    from pathlib import PurePosixPath

    if not racine or not chemin:
        return False
    a, b = canoniser_chemin(racine), canoniser_chemin(chemin)
    if not a or not b:
        return False
    p_racine, p_chemin = PurePosixPath(a), PurePosixPath(b)
    return p_chemin == p_racine or p_racine in p_chemin.parents


__all__ = ["SEPARATEUR", "canoniser_chemin", "canoniser_discriminants",
           "couvre", "empreinte"]
